BugFix : Try to prevent errors like NoMethodError (undefined method 'each' for 1:Fixnum) which are mysteriously only showing in production.  Ruby 1.8.6 error?